### ISSUE TITLE
Dynatrace Deep Monitoring not available on Podtato Server (using Docker)

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [podtato-head/podtato-head#108]
When I deploy podtato-head on Kubernetes and try to monitor it using Dynatrace OneAgent, I end up getting this error message in Dynatrace:

![image](https://user-images.githubusercontent.com/56065213/138231658-5b7b147d-f19f-40c7-bb30-6c787fe24177.png)

I've run into this error before, it's a combination of MUSL/LIBC not being available or properly linked and running the resulting binary in Docker using `FROM scratch`, e.g.:

https://github.com/podtato-head/podtato-head/blob/78d1abc3409e2c7691bf339520472b54faca6c46/podtato-server/docker/DockerfileV0.1.2#L20-L21

https://github.com/podtato-head/podtato-head/blob/78d1abc3409e2c7691bf339520472b54faca6c46/podtato-server/docker/DockerfileV0.1.2#L29-L30

This is a known limitation and can be overcome when using `alpine` as the base image when running the binary. See https://www.dynatrace.com/support/help/technology-support/application-software/go/support/go-known-limitations/#static-monitoring for more information.

**Comment by joshgav** [comment]
Hi @christian-kreuzberger-dtx and @thschue. If I understand correctly, your core issue is that the Dynatrace injected agent expects more OS packages in the app's container than one gets with `scratch` as a base. I suspect many injected agents run as sidecars in their own containers/images and so are okay if a `scratch` container is the base for the _main_ app container.

To track if this is a broader issue I opened #121 and referred to this one. Is this sufficient for now? Thanks!

**Comment by christian-kreuzberger-dtx** [comment]
> If I understand correctly, your core issue is that the Dynatrace injected agent expects more OS packages in the app's container than one gets with scratch as a base.

Partially correct.

The main problem is that when you build your go binaries using alpine, some assumptions are made regarding shared and static libraries (e.g., musl, libc).

In the case of Dynatrace OneAgent, some more information is available here: https://www.dynatrace.com/support/help/technology-support/application-software/go/support/go-known-limitations/#support-for-musl-libc

The easiest fix would be to use alpine for running the binary (e.g., `FROM alpine:3.13`). 
**There are other ways to fix this**, such as playing around with some linkerflags and CGO, e.g.:
```
RUN CGO_ENABLED=0 go build -ldflags '-extldflags "-static"' -o /hello-world
```

**Comment by joshgav** [comment]
Thanks @christian-kreuzberger-dtx. Per this point in the doc you shared: <https://www.dynatrace.com/support/help/technology-support/application-software/go/support/go-known-limitations/#application-binaries-must-be-dynamically-linked> the Dynatrace agent requires that the built binary support ***dynamic linking*** - that is, it must be built with `CGO_ENABLED=1` (Go's default). That fits with the discussion in that same doc about musl - which is only relevant when dynamically linking system libraries at runtime. When CGO is _disabled_ (and libc functionality is embedded in the static build instead) it actually _avoids_ musl/glibc conflicts - but it would cause a problem for an agent which wants to load itself dynamically at runtime :smile: 

More on CGO, musl, libc: <https://www.google.com/search?q=musl+glibc+cgo>

Podtato-head builds in a `golang:alpine` base today, see <https://github.com/podtato-head/podtato-head/blob/main/podtato-services/main/docker/Dockerfile#L1>, but that won't fix your problem cause we disable CGO. And for that reason _running_ in `golang:alpine` won't make a difference either :smile_cat: 

To state again in different terms, if CGO was to be _enabled_ we'd want `golang:alpine` for both build and run (or glibc for both) so as to build and link against the same libc. But since we prefer CGO _disabled_ and static binaries, the runner can be `scratch` since there are no runtime dependencies.

@christian-kreuzberger-dtx if you agree with all this you may ask that we build our binaries for podtato-head with CGO _enabled_ (i.e. `CGO_ENABLED=1`) and also run them in an image with OS libraries like `alpine`, so that other libraries like the Dynatrace agent can be dynamically loaded at runtime. Do you want that?

To be honest, I believe it would be best in the main podtato that we stick with disabling CGO and running in `scratch` for the sake of demonstrating best practices. I'd even advocate for using debian/glibc over alpine/musl for _build_ too because of glibc's maturity, though with CGO disabled it doesn't make a difference to the user.

I also think we should be careful about complicating patterns here for a specific agent - instead, we should encourage users like you to fork and make adjustments for their own work til we know the change is broadly relevant.

@christian-kreuzberger-dtx if you'd like to propose a change here to allow dynamically loading in Go, could you please put together a doc with instructions showing a failure with an agent or two and the proposed change that would fix it? Than we can debate further :)

I'll update the related issue based on this clarification too.

Thank you!

**Comment by christian-kreuzberger-dtx** [comment]
Thanks for your answer, you are correct. Also thanks for updating #121, this should be sufficient now.

I'm not an expert with agents nor dynamically loading things in Go and I cannot provide any more examples for other agents. I only saw the symptom and I know how to fix it for Dynatrace OneAgent. Other agents might have different requirements.

> ... instead, we should encourage users like you to fork and make adjustments for their own work til we know the change is broadly relevant.

This is a good approach, and being an Open Source developer myself I understand and promote this answer myself. It complicates certain things (e.g., I'd have to host the Docker images myself instead of using the official ones), but it's absolutely do-able. I don't think we will see that the change is broadly relevant though.

**Comment by joshgav** [comment]
Thanks @christian-kreuzberger-dtx!
